import type { CalendarEntry } from './types.js'

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC',
  })
}

function summaryRow(e: CalendarEntry): string {
  return `| [${e.name}](#${e.luma_id}) | ${e.event_type} | ${formatDate(e.start_at)} | ${formatDate(e.promo_window_start)} | ${e.dri || '—'} | ${e.copy_status} |`
}

function detailBlock(e: CalendarEntry): string {
  return [
    `## ${e.name}`,
    '',
    `**Luma ID:** ${e.luma_id}`,
    `**Type:** ${e.event_type}`,
    `**Dates:** ${formatDate(e.start_at)} – ${formatDate(e.end_at)}`,
    `**Timezone:** ${e.timezone}`,
    `**Registration:** ${e.luma_url}`,
    e.meeting_url ? `**Meeting URL:** ${e.meeting_url}` : null,
    `**Promo Window Opens:** ${formatDate(e.promo_window_start)}`,
    `**DRI:** ${e.dri || '—'}`,
    `**Copy Status:** ${e.copy_status}`,
    '',
    '### Channel Plan',
    e.channel_plan || '*(Generated by promo planner — Phase 4)*',
    '',
    '### Notes',
    e.notes || '*(No description)*',
    '',
    '---',
  ].filter((line): line is string => line !== null).join('\n')
}

export function renderCalendar(entries: CalendarEntry[], syncedAt: string): string {
  const header = [
    '# WDAI Content Calendar',
    '',
    `> Last synced from Luma: ${formatDate(syncedAt)}`,
    '',
    '---',
    '',
    '## Upcoming Events',
    '',
    '| Event | Type | Start | Promo Window | DRI | Copy Status |',
    '|-------|------|-------|--------------|-----|-------------|',
    ...entries.map(summaryRow),
    '',
    '---',
    '',
  ].join('\n')

  const details = entries.map(detailBlock).join('\n\n')

  return header + details + '\n'
}
